Repository DstMlOpsCrypto/MainCrypto, pull requests merged in 2024-09, with the labels that each got.

#56 Feat 036
  Dockerfile
  README.md
  airflow/dags/crypto_ohcl_dag.py
  airflow/logs/scheduler/latest
  dags/crypto_ohcl_dag.py
  db/Dockerfile
  db/create_tables.sql
  docker-compose.yml
  local_docker_clean.sh
  local_docker_install.sh
  local_dockercompose_remove.sh
  logs/scheduler/latest
  requirements.txt
Labels: enhancement

#57 Feat 036
  README.md
  airflow/dags/crypto_ohcl_dag.py
  airflow/logs/scheduler/latest
  dags/crypto_ohcl_dag.py
  docker-compose.yml
  logs/scheduler/latest
Labels: documentation, enhancement

#61 Feat 0058 connexion bdd api
  .gitignore
  API/Dockerfile
  API/app/crypto/__init__.py
  API/app/crypto/router.py
  API/app/database.py
  API/app/main.py
  airflow/logs/scheduler/latest
  docker-compose.yml
Labels: bug, enhancement

#64 Feat_0063: Connexion BDD à toutes les routes de l'API
  API/Dockerfile
  API/app/auth/database.py
  API/app/auth/router.py
  API/app/auth/schemas.py
  API/app/auth/security.py
  API/app/auth/utils.py
  API/app/authentification/__init__.py
  API/app/authentification/router.py
  API/app/authentification/security.py
  API/app/authentification/utils.py
  API/app/crypto/router.py
  API/app/database.py
  API/app/main.py
  API/app/ml/__init__.py
  API/app/ml/database.py
  API/app/ml/models.py
  API/app/ml/router.py
  API/gunicorn_conf.py
  API/tests/conftest.py
  API/tests/test_auth.py
  API/tests/test_authentification.py
  API/tests/test_crypto.py
  API/tests/test_ml.py
  airflow/logs/scheduler/latest
  db/create_tables.sql
  docker-compose.yml
  frontend/pages/account.py
  frontend/pages/create_user.py
  frontend/pages/home.py
  frontend/utils/api_client.py
  frontend/utils/data_loader.py
Labels: bug, enhancement
